import localFont from "next/font/local";
import "../scss/index.scss";
const freeMan = localFont({ src: "../../public/Freeman-Regular.ttf" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={freeMan.className}>{children}</body>
    </html>
  );
}
